### PR TITLE
Feature / Use Marked and render source codes

### PR DESCRIPTION
**Pull request by paulodiovani**
I've changed showdown to Marked, as it's, in my opinion, a better replacement for gfm.

I also added some basic support for rendering source code files (they're still not listed on directories, but can be rendered with direct link).

It's just some languages for now. The plan is to support all languages that highlight.js support later.

Note: This PR replaces #20

### CODE REVIEW

**Comment by youurayy** [comment]
Looking good, assuming it's tested, merging in. Thanks!

**Comment by paulodiovani** [comment]
actually I was still working on it :sweat_smile:

**Comment by youurayy** [comment]
🤦‍♂ lol, anyhow, let me know which PR's to review and approve next

**Comment by youurayy** [comment]
add your name into changelog/about

**Pull request merged**
